version: "3.3"
services:
  db:
    image: mongo
    restart: always
    volumes:
      - app-db-data:/data/db
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .env
    depends_on:
      - db
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  backend:
    image: backend
    depends_on:
      - db
    ports:
      - 4000:4000
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app

volumes:
  app-db-data:
